"""Add renter_id to properties

Revision ID: 2447d683ff79
Revises: 
Create Date: 2024-09-23 10:01:49.709941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2447d683ff79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renter_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['renter_id'])
        batch_op.create_foreign_key(None, 'renter', ['renter_id'], ['id'])

    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('renter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('due_date')
        batch_op.drop_column('amount')

    with op.batch_alter_table('renter', schema=None) as batch_op:
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renter', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=9), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('payment_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('renter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('payment_status')
        batch_op.drop_column('amount_paid')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('renter_id')

    # ### end Alembic commands ###
